
import Classes.Conexao;
import Classes.Imprimir;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class EntradaSaidaDinheiro extends javax.swing.JFrame {

    /**
     * Creates new form EntradaSaidaDinheiro
     */
    
    Conexao con = new Conexao();
    ResultSet rs;
    double valor=0;
    Imprimir i = new Imprimir();
    DecimalFormat df =  new DecimalFormat("0.00");
    
    public EntradaSaidaDinheiro() {
        initComponents();
        jCBMovimento.requestFocus();
        EnterPraIrProValor();
        ConfiguraESC();
        URL url = this.getClass().getResource("/imagens/ícone.png");  
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);  
        this.setIconImage(iconeTitulo);
        ConfiguraCloseOperation();
    }
    
    private void ConfiguraCloseOperation(){
        addWindowListener(
            new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent we) {
                    TelaPrincipal.AparecerTela=true;
                    dispose();
                }
            }
	);
    }
    
    private void EnterPraIrProValor(){
        InputMap inputMap2 = this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap2.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0),"forward2");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap2);
        this.getRootPane().getActionMap().put("forward2", new AbstractAction(){
            private static final long serialVersionUID = 1L;
            @Override
            public void actionPerformed(ActionEvent arg0) {
                jTFValor.requestFocus();
                EnterPraSalvar();
            }
        });
    }
    
    private void EnterPraSalvar(){
        InputMap inputMap2 = this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap2.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0),"forward2");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap2);
        this.getRootPane().getActionMap().put("forward2", new AbstractAction(){
            private static final long serialVersionUID = 1L;
            @Override
            public void actionPerformed(ActionEvent arg0) {
                jBSalvarActionPerformed(arg0);
            }
        });
    }
    
    private void ConfiguraESC(){
        InputMap inputMap = this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),"forward");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("forward", new AbstractAction(){
            private static final long serialVersionUID = 1L;
            @Override
            public void actionPerformed(ActionEvent arg0) {
                TelaPrincipal.AparecerTela=true;
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCBMovimento = new javax.swing.JComboBox<>();
        jLMovimento = new javax.swing.JLabel();
        jTFValor = new javax.swing.JTextField();
        jLValor = new javax.swing.JLabel();
        jBSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("LC - Entrada/Saída de Dinheiro");
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });

        jCBMovimento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<< Selecione >>", "Sangria de Dinheiro", "Suprimento de Dinheiro" }));

        jLMovimento.setText("Movimento:");

        jTFValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFValorFocusGained(evt);
            }
        });

        jLValor.setText("Valor:");

        jBSalvar.setText("Confirmar");
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLValor)
                            .addComponent(jLMovimento)
                            .addComponent(jTFValor, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jBSalvar)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLMovimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jBSalvar)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed
        // TODO add your handling code here:
        getContentPane().setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        if (jCBMovimento.getSelectedIndex()>0){
            try {
                valor=Double.parseDouble(jTFValor.getText().replace(",","."));
                String timeStamp = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(Calendar.getInstance().getTime());
                if (valor>0){
                    switch (jCBMovimento.getSelectedIndex()){
                        case 1:
                            if (TelaPrincipal.saldo_atual>=valor){
                                long unixTime = System.currentTimeMillis() / 1000L;
                                try {
                                    con.Insert("INSERT INTO fc_movimento (id_fc_caixa, id_fc_evento, id_fc_operador, pdv_movimento, datahora_movimento, tipo_movimento, descricao_movimento, itens_movimento, valor_movimento, dinheiro_movimento, troco_movimento, mktime_movimento, integra_movimento) VALUES ("+TelaPrincipal.Id_CaixaAberto+", "+TelaPrincipal.Id_eventoAtivo+", "+TelaPrincipal.id_operadorAtivo+", "+TelaPrincipal.pdvAtivo+", '"+timeStamp+"', 3, 'Sangria Caixa', 0, -"+valor+", 0, 0, "+unixTime+", 0)");
                                    rs=con.Select("SELECT saldo_caixa FROM fc_caixa USE INDEX (id_fc_caixa) WHERE id_fc_caixa="+TelaPrincipal.Id_CaixaAberto);
                                    while (rs.next()){
                                        double saldoAntigo = Double.parseDouble(rs.getString("saldo_caixa").replace(",", "."));
                                        double saldoAtual = saldoAntigo-valor;
                                        con.Insert("UPDATE fc_caixa USE INDEX (id_fc_caixa) SET saldo_caixa="+saldoAtual+" WHERE id_fc_caixa="+TelaPrincipal.Id_CaixaAberto);
                                    }
                                    rs=con.Select("SELECT sangria FROM fc_config LIMIT 1");
                                    while (rs.next()){
                                        for (int x=0;x<rs.getInt("sangria");x++){
                                            //i.ImprimeFuncao(TelaPrincipal.img_eventoAtivo, TelaPrincipal.Id_eventoAtivo, TelaPrincipal.nome_eventoAtivo, "Sangria Caixa", "-"+df.format(valor), TelaPrincipal.OperadorAtivo, String.valueOf(TelaPrincipal.pdvAtivo), TelaPrincipal.img_eventoAtivo);
                                        }
                                    }
                                } catch (SQLException ex) {
                                    JOptionPane.showMessageDialog(null, "Erro na conexão com o banco de dados", "LC - Entrada/Saída de Dinheiro", JOptionPane.ERROR_MESSAGE);
                                    Logger.getLogger(EntradaSaidaDinheiro.class.getName()).log(Level.SEVERE, null, ex);
                                }
                                dispose();
                                TelaPrincipal.SangrouSuprimiu=true;
                                TelaPrincipal.AparecerTela=true;
                            } else {
                                JOptionPane.showMessageDialog(null, "Valor de sangria maior que o valor em caixa", "LC - Entrada/Saída de Dinheiro", JOptionPane.ERROR_MESSAGE);
                                jTFValor.setText("");
                                jTFValor.requestFocus();
                            }
                            break;
                        case 2:
                            try {
                                long unixTime = System.currentTimeMillis() / 1000L;
                                con.Insert("INSERT INTO fc_movimento (id_fc_caixa, id_fc_evento, id_fc_operador, pdv_movimento, datahora_movimento, tipo_movimento, descricao_movimento, itens_movimento, valor_movimento, dinheiro_movimento, troco_movimento, mktime_movimento, integra_movimento) VALUES ("+TelaPrincipal.Id_CaixaAberto+", "+TelaPrincipal.Id_eventoAtivo+", "+TelaPrincipal.id_operadorAtivo+", "+TelaPrincipal.pdvAtivo+", '"+timeStamp+"', 5, 'Suprimento Caixa', 0, "+valor+", 0, 0, "+unixTime+", 0)");
                                rs=con.Select("SELECT saldo_caixa FROM fc_caixa USE INDEX (id_fc_caixa) WHERE id_fc_caixa="+TelaPrincipal.Id_CaixaAberto);
                                while (rs.next()){
                                    double saldoAntigo = Double.parseDouble(rs.getString("saldo_caixa").replace(",", "."));
                                    double saldoAtual = saldoAntigo+valor;
                                    con.Insert("UPDATE fc_caixa USE INDEX (id_fc_caixa) SET saldo_caixa="+saldoAtual+" WHERE id_fc_caixa="+TelaPrincipal.Id_CaixaAberto);
                                }
                                rs=con.Select("SELECT suprimento FROM fc_config LIMIT 1");
                                while (rs.next()){
                                    for (int x=0;x<rs.getInt("suprimento");x++){
                                        //i.ImprimeFuncao(TelaPrincipal.img_eventoAtivo, TelaPrincipal.Id_eventoAtivo, TelaPrincipal.nome_eventoAtivo, "Suprimento Caixa", df.format(valor), TelaPrincipal.OperadorAtivo, String.valueOf(TelaPrincipal.pdvAtivo), TelaPrincipal.img_eventoAtivo);
                                    }
                                }
                            } catch (SQLException ex) {
                                JOptionPane.showMessageDialog(null, "Erro na conexão com o banco de dados", "LC - Entrada/Saída de Dinheiro", JOptionPane.ERROR_MESSAGE);
                                Logger.getLogger(EntradaSaidaDinheiro.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            dispose();
                            TelaPrincipal.SangrouSuprimiu=true;
                            TelaPrincipal.AparecerTela=true;
                            break;
                        default:
                            break;
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor, informe um valor positivo", "LC - Entrada/Saída de Dinheiro", JOptionPane.ERROR_MESSAGE);
                    jTFValor.requestFocus();
                    jTFValor.setText("");
                }
            } catch (NumberFormatException n){
                JOptionPane.showMessageDialog(null, "Por favor, informe um valor válido", "LC - Entrada/Saída de Dinheiro", JOptionPane.ERROR_MESSAGE);
                jTFValor.requestFocus();
                jTFValor.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, selecione um movimento", "LC - Entrada/Saída de Dinheiro", JOptionPane.ERROR_MESSAGE);
            jCBMovimento.requestFocus();
            jTFValor.setText("");
            EnterPraIrProValor();
        }
        getContentPane().setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jBSalvarActionPerformed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
        requestFocus();
        toFront();
    }//GEN-LAST:event_formWindowLostFocus

    private void jTFValorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFValorFocusGained
        // TODO add your handling code here:
        EnterPraSalvar();
    }//GEN-LAST:event_jTFValorFocusGained

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSalvar;
    private javax.swing.JComboBox<String> jCBMovimento;
    private javax.swing.JLabel jLMovimento;
    private javax.swing.JLabel jLValor;
    private javax.swing.JTextField jTFValor;
    // End of variables declaration//GEN-END:variables
}
